### ISSUE TITLE
Inserting Comment field in Excel spreadsheet

### ISSUE THREAD

**Issue by dptsay** [dfinke/ImportExcel#648] opened 2019-08-05 20:45 UTC
I am having problems updating the comment field of Excel Cells through Importexcel and did not know what I have done wrong.
(1) I created a spreadsheet using Excel program, and arbitrary pick Cell: B2 to insert a value and a comment.  I then use Importexcel to open the spreadsheet file and read in the cell comment and assigned to variable say $tmp and is OK.
(2) I then add some new text comment to $tmp (so it contains old and new comments), I remove the comment field of Cell B2 and then append the $tmp as comment to Cell B2 and close-excelpackage with save.
(3) I use the Microsoft Excel to open up the spreadsheet and the new and old comments are in there, Cell B2, but when I use Powershell to open-excelpackage and read the Cell B2 comment field and it is Blank.

**Comment by jhoneill** [comment] 2019-08-15 15:06
I have seen that the way EPPlus handles comments isn't very robust, which is one of the reasons we haven't put comments into the PowerShell module. 
If you would like to share the script / Excel file which is giving the problem we may be able to find a work around but it is a problem area I'm afraid.

**Comment by dptsay** [comment] 2019-08-15 17:33
[Book1.xlsx](https://github.com/dfinke/ImportExcel/files/3506531/Book1.xlsx)
Thanks for getting back to me.  Attached excel is a blank file only with a comment inserted at B2.
There is no problem updating the comment field, but once I save it to a different file name and open that file, the comment field is blank, however when I use Microsoft Excel to open it, the comment is OK. 
The following is the script:
Import-module importexcel
$master = Open-ExcelPackage -Path c:\Temp\Book1.xlsx
$B2comments = $master.workbook.worksheets["Sheet1"].cells["B2"].Comment.text
$NewB2Comments = $B2comments + " Inserted Comment"
$CellB2 = $master.workbook.worksheets["Sheet1"].cells["B2"]
$master.workbook.worksheets["Sheet1"].comments.remove($CellB2.comment)
$master.workbook.worksheets["Sheet1"].cells["B2"].addcomment($NewB2Comments, 'User')
 $master.workbook.worksheets["Sheet1"].cells["B2"].Comment.text
close-excelpackage $master -SaveAs "C:\Temp\Book2.xlsx"

$Updatedmaster = Open-ExcelPackage -Path "C:\Temp\Book2.xlsx"
$Q = $Updatedmaster.workbook.worksheets["Sheet1"].cells["B2"].Comment.text

**Comment by jhoneill** [comment] 2019-08-16 15:17
I have done a little bit more digging. It turns out this is issue is fixed in a newer version of EPPlus, unfortunately we're not using that version because it introduces some other regressions - 7 tests in the current suite break. In the version we're using comments are broken, although this has showed me another dimension to how broken.

**Comment by dfinke** [comment] 2019-08-16 16:01
How bad are the breaks? Are they across functionality or more narrow? Not sure it's worth upgrading yet. I was interested in a newer version to implement sparklines, had it working in a branch.

**Comment by jhoneill** [comment] 2019-08-16 18:02
One is around activating a worksheet. 
One on conditional formatting, and multiple around extending data in a pivot table. 
I haven't drilled into them too deeply, and I don't have the very latest DLL. (can't recall where I got the compiled one from but it's 4.5.2.1 and the latest sources are 4.5.3.2 IIRC )

**Comment by dfinke** [comment] 2019-08-16 18:45
I usually grab it here https://www.nuget.org/packages/EPPlus/
Looks like 4.5.3.2. I'll see if I can kick the tires.

Their notes:
>Breaking change in .NET Core: The Worksheets collection will be zero based as default.
This can be altered by setting the ExcelPackage.Compatibility.IsWorksheets1Based to true.

**Comment by jhoneill** [comment] 2019-08-16 21:19
4.5.3.2 breaks validation as well ...

**Closed** 2020-05-02 14:24 UTC
