### ISSUE TITLE
EPPlus v4.5.3.2

### ISSUE THREAD

**Issue by dfinke** [dfinke/ImportExcel#660] opened 2019-08-16 23:09 UTC
## Fails out of the box

@jhoneill this is gonna be fun :(

![image](https://user-images.githubusercontent.com/67258/63202759-4e500480-c059-11e9-9de6-8fbe34213836.png)

**Comment by jhoneill** [comment] 2019-08-17 10:47
Hmm. I ran a full test pass and got 8 fails and 193 passes. Could be a whole bunch of things to chase down. 
BTW this is one of the places where the error handling could be clearer.

**Comment by dfinke** [comment] 2019-08-17 15:40
Putting this here for later reference. I just dropped the new dll in and ran the tests.
Similar errors, maybe one fix to solve them.
[testResults.xlsx](https://github.com/dfinke/ImportExcel/files/3512156/testResults.xlsx)

Used this PS script - https://github.com/dfinke/ImportExcel/blob/master/Examples/InteractWithOtherModules/Pester/Analyze_that.ps1

I'm running:

![image](https://user-images.githubusercontent.com/67258/63214239-c7943980-c0e3-11e9-94bf-cb2ba993fdf5.png)

**Comment by jhoneill** [comment] 2019-08-18 00:26
OK ... I've got it working and all the tests now pass. (Though for reasons I don't understand code was still finding the DLL in the \program files\windowsPowershell\modules ... not the dev directory. 

Fails I had were down to two regressions and two improvements 
Regression #1 is checking the active worksheet. When the workbook is opened none of the sheets has .View.TabSelected = True .... 
one of them them must be active ,and the selected one is active when opening in Excel. I filed a bug for this (284) a year and a few days ago. No repsonse. 

Regression #2 is when the sheet is read the HighValue / LowValue / Medium Value are blank on conditional format. They can be set just fine, just not read back 

(I have two other bugs open on EPPLus one is the filter on a table being turned back on if it is off and the file is loaded into EPPLus. The other concerns setting axis positions on a chart). 

Improvement #1 is the XML to extend the data area for a pivot table is no longer needed and doesn't work, but I've done a fix for that. 

And the last is that pivot tables linked a range now link to the range itself, where before it linked to the cells that range mapped to (so if the range changed the pivot didn't get the new data) I've fixed the broken test for that.

**Comment by dfinke** [comment] 2019-08-18 13:22
Sounds good. I was copying over the netstandard2.0 dll, had removed the module in the ps module path. The net40 dll turns up the 8 tests with issues.

EPPlus will update but now .NET Core uses a preview of System.Drawing.Common. I think .NET core is doing GA September, then the LTS in November. So another version of EPPlus maybe sometime first quarter 2020?

Not sure how much re-work on this re-work if any.

What do you think?

**Comment by jhoneill** [comment] 2019-08-19 14:04
I'll try to do a PR shortly because I've got the tests working. 
We'll just have to wait and see what effect changes on .NET have and what  copes from Jan on the EPPlus front. I don't think any of the things I logged a year ago as problems with 4.5 have been touched ... so I'm not sure how active the development is. 
I'm not sure if we should try to contribute to EPPlus  (would contributions get merged ?) or even have separate fork of EPPlus (which feels wrong). 
My gut feel is - all other things being equal - we should use the latest (stable) version of EPPlus. There are two regressions mentioned above, plus one to do hacking XML for chart axes, and one on adding the filter back to tables where it has been turned off. Those are livable with. When a future release arrives - cross that bridge when we get to it.

**Comment by dfinke** [comment] 2019-08-19 19:21
Agreed on all points. Don't know enough about the EPPlus flow to know what they accept, I'm not up for maintaining a fork. 

Do a PR. Hope their latest version is stable. 

We'll see what they deliver next. 

Was going to merge this, let me know if you want me to wait. 

https://github.com/dfinke/ImportExcel/pull/661

**Comment by dfinke** [comment] 2019-08-21 21:10
@jhoneill I merged #661

**Comment by jhoneill** [comment] 2019-08-23 09:58
OK. I'll get everything updated my side and do a PR, but then I'm (we're) committed to the new EPPlus. The new version is stable in the sense that there's a decent time since release so any big breaks should have appeared. Rolling back would be a pain, but not a catastrophe.

**Comment by dfinke** [comment] 2019-08-23 11:36
Sounds good. I have a tagged release https://github.com/dfinke/ImportExcel/releases/tag/v6.2.4, plus it's in the PS gallery. Should make rolling back a bit easier.

**Comment by dfinke** [comment] 2019-08-25 16:06
@jhoneill added another build pipeline for that runs Windows, Linux and Mac. Kept the previous ones. When I can I'll break these out to separate pipelines.

[![Build Status](https://dougfinke.visualstudio.com/ImportExcel/_apis/build/status/dfinke.ImportExcel?branchName=master)](https://dougfinke.visualstudio.com/ImportExcel/_build/latest?definitionId=20&branchName=master)

**Comment by ili101** [comment] 2019-08-25 16:08
Is this in preparation for PowerShell 7? I just finished updating my module to support PS7 (https://github.com/ili101/Join-Object).

Since most open source PowerShell modules need the same supporting structure I took this part out and created a template from it that can be shared and reused for any module https://github.com/ili101/Module.Template.
It includes mostly the CI stuff using AppVeyor and Azure Pipelines testing on PS Framework and Core 7 preview on Linux and Windows. It makes Artifacts, Publish the Pester test results and can optionally deploy to the gallery.
I kept it simple and it should be familiar to you as it's inspired in part by what you have here. for example Install.ps1 is the combination of Install.ps1 and InstallModule.ps1 with some fixes.

If you like after you are done with the EPPlus update I can make a PR to see how it fits and if you have improvements ideas we can update the template so whoever will use it will benefit.

**Comment by jhoneill** [comment] 2019-08-25 16:13
There isn't a link between this and PS7. We might find with the one problem we know of in EPPlus on Linux/Mac with PS 6 goes away with the new .Net in 7. 

I'm trying get the bits I have which fix differences between EPPlus 4.0 and 4.5 uploaded and then we can settle on the new (and stable) version of it.

**Comment by dfinke** [comment] 2019-08-25 16:15
Yes, this is a multifaceted alignment. It's primarily about moving to the latest EPPlus version. Folks have been able to run ImportExcel cross platform. EPPlus is not ported, and cannot finish till .NET core is GA in a couple months.

The OS matrix for the tests is missing Windows PS Core.

Once @jhoneill does a PR for the upgrades he did, figured the new Azure DevOps pipeline would be a good smoke test for xplat. Then, refactoring of the pipelines, display etc. would be next.

**Comment by dfinke** [comment] 2019-08-25 16:17
@ili101 could probably use your work in my https://github.com/dfinke/PSKit and https://github.com/dfinke/PSStringScanner repos.

**Closed** 2020-05-02 14:24 UTC
