### ISSUE TITLE
Error When Exporting Excel File with Multiple Sheets with Pivot Tables for Each One

### ISSUE THREAD

**Issue by msmolin1** [dfinke/ImportExcel#768] opened 2020-01-20 21:05 UTC
It seems that certain pivot tables (for both small and large worksheets) are getting corrupted with the following error. Any ideas?

Removed Feature: PivotTable report from /xl/pivotCache/pivotCacheDefinition1.xml part (PivotTable cache)
Removed Feature: PivotTable report from /xl/pivotTables/pivotTable1.xml part (PivotTable view)
Removed Records: Workbook properties from /xl/workbook.xml part (Workbook)
Repaired Records: Table from /xl/tables/table1.xml part (Table)

**Comment by pkarunkar** [comment] 2020-01-20 21:30
Can you give us a sample. ?
Are you creating the Excel sheet Everytime or just overwriting existing Excel.?

**Comment by msmolin1** [comment] 2020-01-20 22:20
Unfortunately, the data i am using is confidential. 

Here's what I'm basically doing: I create a worksheet per VP name at my company that has all their reports under it.  I wrote some functions in PowerShell that basically take my input objects and create a list of hashtables for them with all the parameters required to do Export-Excel (like the worksheet name and the output file path).

I iterate through that list and run Export-Excel against against calculated properties for the name and the corresponding value of each parameter, like this:

$outputparams = @{
PivotTableName                 "Doe, John-Pivot"
NoTotalsInPivot                False
PassThru                       False
PivotTotals                    Both
BoldTopRow                     True
TableName                      System.Object
OutBuffer                      0
ShowCategory                   False
Path                           D:\Git\PhishingReporting\Reports\AHS-Phishing-Reporting-Summary-2020-01-20-03-36-39.xlsx
MoveBefore                     System.Object
AutoFilter                     True
ChartType                      Pie
StartRow                       1
HideSheet                      False
UnHideSheet                    {}
IncludePivotChart              True
}

Export-Excel @outputparams

It outputs all the worksheets and works great.

The only issue as mentioned is that some pivot tables get corrupted. It also appears that not the same tables get corrupted every time, which is strange.

If what I said is esoteric, let me know and I can share my code.

Thanks,
Mike

**Comment by pkarunkar** [comment] 2020-01-20 23:15
ok Just from looking at your Params.

Hashtable takes assignment for each parameter.
$outputparams = @{
PivotTableName  = "Doe, John-Pivot"
NoTotalsInPivot  = $False
OutBuffer =  0
Path =  "D:\Git\PhishingReporting\Reports\AHS-Phishing-Reporting-Summary-2020-01-20-03-36-39.xlsx"
AutoFilter = $True
ChartType = "Pie"
StartRow = 1
IncludePivotChart  = $True
} 

I am not sure why you are including all the switch parameters. By default, it is false if you don't use it. 
I have never tried $true $false in place of Hash Params. Will try it.

**Comment by msmolin1** [comment] 2020-01-21 16:50
Sorry, let me clarify what's happening: The first sheet that is being output is 22,000+ rows of data (i think 12 columns wide or so).

If I automate outputting just that data and its corresponding pivot table/report to a file via Export-Excel, it works fine. If I try to generate more reports for additional worksheets that will be exported to the same file, however, the report for the fist sheet of 22,000 records will break; everything else is usually fine, but it seems that at least sometimes additional reports get corrupted.

There are 37 individual worksheets that I am exporting to a single Excel file iteratively.

If i don't generate the reports and just output the raw data of 37 worksheets (the first one containing an aggregate of all the data in the following 36), then it works perfectly every time.

I hope that helps.

Mike

**Comment by lime12892** [comment] 2020-02-12 22:27
Having this same problem. I found the difference to be between the ImportExcel versions 6.2.4 -> 6.5.0. My code works fine in 6.2.4, but has the issue in 6.5.0.

Additionally, if I move the EPPlus.dll file (version 4.0.5.0) from ImportExcel 6.2.4 and replace it on ImportExcel 6.5.0 (EPPlus.dll version 4.5.3.2), then it works again. Obviously this isn't recommended, but goes to show that the problem appears to be with EPPlus.

I would recommend downgrading ImportExcel to 6.2.4 if you don't rely on anything that's been introduced since then.

**Comment by dfinke** [comment] 2020-02-13 00:43
@lime12892 Thanks for tracking down those clues. Need to see the impact of using 4.0 in the later version of ImportExcel.

@jhoneill Potential EPPlus issue. Plus, EPPlus is moving to a different model and bug fixes may not done any longer on their current product.

**Comment by jhoneill** [comment] 2020-02-14 18:44
Hmm... I wish them luck, genuinely, but "we have a free version which has been around for years, so how do you fancy paying for the next version" isn't a great business model - besides the aggravation of getting a large company to pay small sums for software.

**Closed** 2020-05-02 14:33 UTC

**Comment by napcadev** [comment] 2020-06-15 18:42
I am getting the same issue with the following code.

The second pivottable is generated, but the first one is removed, leaving the blank sheet behind.

```
$t = import-csv DublinTraceSender.csv
$excel = $t | export-excel BCMMailTrace.xlsx -worksheetname "Dublin Send Trace"  -tablename DublinSenders -autosize -autofilter -passthru

$excel.Workbook.Worksheets.Add("Dublin Send Count")

$pivotTableParams = @{
  PivotTableName  = "Dublin Send Count"
  SourceWorkSheet = $excel."Dublin Send Trace"
  PivotRows       = "SenderAddress"
  PivotData       = @{'senderaddress' = 'count' }
}

$pt = Add-PivotTable -ExcelPackage $excel @pivotTableParams -PassThru

Close-ExcelPackage $excel

$t = import-csv MaynoothTraceSender.csv
$excel = $t | export-excel BCMMailTrace.xlsx -worksheetname "Maynooth Send Trace"  -tablename MaynoothSenders -autosize -autofilter -passthru

$excel.Workbook.Worksheets.Add("Maynooth Send Count")

$pivotTableParams = @{
  PivotTableName  = "Maynooth Send Count"
  SourceWorkSheet = $excel."Maynooth Send Trace"
  PivotRows       = "SenderAddress"
  PivotData       = @{'senderaddress' = 'count' }
}

$pt = Add-PivotTable -ExcelPackage $excel @pivotTableParams -PassThru

Close-ExcelPackage $excel
```

**Comment by dfinke** [comment] 2020-06-15 18:45
Please could you post a repro with data, etc.

**Comment by napcadev** [comment] 2020-06-15 19:01
@dfinke I have had to anonymise the data, but these are the same format as the files I am dealing with.
[https://github.com/napcadev/senders](url)
Thanks.

**Comment by napcadev** [comment] 2020-06-15 19:10
I am using version 7.0.1 btw.

**Comment by dfinke** [comment] 2020-06-15 20:09
There's a bug. Only have a workaround, remove the `-TableName` on both `Export-Excel`. I think there is a bug in the DLL, not confirmed, which is maintained by other folks. I was able to add the table names manually when the xlsx was open (didn't try the colorization).

**Comment by napcadev** [comment] 2020-06-15 20:12
Brilliant, that works.  Many thanks for your help!.
