### ISSUE TITLE
ConvertFrom-ExcelToSqlInsert does not escape single quotes

### ISSUE THREAD

**Issue by DerValle** [dfinke/ImportExcel#525] opened 2019-01-16 17:50 UTC
When I use the CmdLet on an Excel Sheet that contains text with single quotes, I get lot's of faulty quieries.
I would expect that the CmdLet makes sure that queries work regardless of the data quality.

Best regards and happy hacking

**Comment by dfinke** [comment] 2019-01-16 17:56
Please, could you post and example xlsx file

**Comment by beckerben** [comment] 2019-11-20 13:06
duplicate of #512

**Closed** 2019-11-24 15:35 UTC
Labels: Investigate
