### ISSUE TITLE
problem with Import-Excel

### ISSUE THREAD

**Issue by kap260** [dfinke/ImportExcel#921] opened 2020-09-15 17:50 UTC
All of a sudden (worked yesterday), I am getting this error:
Exception calling "Load" with "1" argument(s): "The file is not an valid Package file. If the file is encrypted, please supply the password in the constructor."

When I run this command:
$ImportData = import-excel -path $NeededFile -WorksheetName $WSName -StartRow 4

I would appreciate any help!
Kirk Peterson

**Comment by gbeifuss** [comment] 2020-09-18 19:19
I think that I have the same issue.
I wrote a script using this module that should run daily (and has, for months). However, it's not run since September 15th. When I manually run "Open-ExcelPackage -Path \\FileServer\IT\HyperV_inventory.xlsx", this error is now returned:
```
New-Object: C:\Users\USERNAME\Documents\PowerShell\Modules\ImportExcel\7.1.0\Public\Open-ExcelPackage.ps1:34:35
Line |
  34 |  …  {$pkgobj = New-Object -TypeName OfficeOpenXml.ExcelPackage -Argument …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling ".ctor" with "1" argument(s): "  Bad signature (0xEDBDC8FC) at position  0x0002360B"
```

I tried updating to the latest module (7.1.1), but it has the same issue.

**Comment by dfinke** [comment] 2020-09-18 21:10
Please upload a simple repro of the issue

**Comment by gbeifuss** [comment] 2020-09-18 21:32
Hope that this is sufficient.
```

PowerShell 7.0.3
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/powershell
Type 'help' to get help.

PS C:\Windows\System32> Open-ExcelPackage -Path \\fileserver\IT\HyperV_inventory.xlsx
New-Object: C:\Users\admin\Documents\PowerShell\Modules\ImportExcel\7.1.1\Public\Open-ExcelPackage.ps1:34
Line |
  34 |  …  {$pkgobj = New-Object -TypeName OfficeOpenXml.ExcelPackage -Argument …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling ".ctor" with "1" argument(s): "  Bad signature (0xEDBDC8FC) at position  0x0002360B"

PS C:\Windows\System32>
```

**Comment by dfinke** [comment] 2020-09-19 13:53
What version of ImportExcel are you running? Can you run `Import-Excel` the function against it and pull out data from an existing sheet?

**Comment by gbeifuss** [comment] 2020-09-19 15:28
Hi Doug,

I was running 7.1.0 (for many months), but when I started getting this error, I did a forced install of 7.1.1 in hopes of resolving the error.
I'm happy to privately send you the spreadsheet and/or my script, if that'd help. I get the same error if the spreadsheet is local:

```PS Microsoft.PowerShell.Core\FileSystem::\\cns\tsg\Documentation\Powershell Repository> $excel = Open-ExcelPackage -Path c:\HyperV_inventory.xlsx

New-Object: C:\Users\gbadmin\Documents\PowerShell\Modules\ImportExcel\7.1.0\Public\Open-ExcelPackage.ps1:34:35
Line |
  34 |  …  {$pkgobj = New-Object -TypeName OfficeOpenXml.ExcelPackage -Argument …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling ".ctor" with "1" argument(s): "  Bad signature (0xEDBDC8FC) at position  0x0002360B"




PS C:\Windows\System32> Get-InstalledModule importexcel

Version              Name                                Repository           Description
-------              ----                                ----------           -----------
7.1.1                ImportExcel                         PSGallery            PowerShell module to import/export Excel…




PS C:\Windows\System32> Import-Excel -Path \\fileserver\IT\HyperV_inventory.xlsx
MethodInvocationException: C:\Users\admin\Documents\PowerShell\Modules\ImportExcel\7.1.1\Public\Import-Excel.ps1:113
Line |
 113 |                  else { $ExcelPackage.Load($stream) }
     |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "Load" with "1" argument(s): "  Bad signature (0xEDBDC8FC) at position  0x0002360B"

WARNING: Selecting columns 1 to 0 might give odd results.
Exception: C:\Users\gbadmin\Documents\PowerShell\Modules\ImportExcel\7.1.1\Public\Import-Excel.ps1:216
Line |
 216 |  …     catch { throw "Failed importing the Excel workbook '$Path' with w …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Failed importing the Excel workbook '\\fileserver\IT\HyperV_inventory.xlsx'
     | with worksheet '': Failed creating property names: Cannot index into a null array.

```

**Comment by dfinke** [comment] 2020-09-19 15:53
Does this error on any xlsx file you point to?

**Comment by gbeifuss** [comment] 2020-09-19 16:05
Actually, no - some do open (which I should have tested earlier).
Since that's the case, maybe it's just something corrupt in that particular file - I'll rebuild it on Monday and try this again.


```
PS C:\Windows\System32> $excel = Open-ExcelPackage -Path '\\fileserver\IT\\critical servers.xlsx'

PS C:\Windows\System32> $excel = Open-ExcelPackage -Path \\fileserver\IT\\Hyper-V_clustering.xlsx

PS C:\Windows\System32> $excel = Open-ExcelPackage -Path \\fileserver\IT\\HyperV_inventory.xlsx

New-Object: C:\Users\admin\Documents\PowerShell\Modules\ImportExcel\7.1.0\Public\Open-ExcelPackage.ps1:34:35
Line |
  34 |  …  {$pkgobj = New-Object -TypeName OfficeOpenXml.ExcelPackage -Argument …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling ".ctor" with "1" argument(s): "  Bad signature (0xEDBDC8FC) at position  0x0002360B"
```

**Comment by dfinke** [comment] 2020-09-19 16:15
It does point to the issue is with the xlsx.

**Comment by gbeifuss** [comment] 2020-09-23 11:21
I deleted all content on both dynamically generated sheets, reran the script and everything worked.

**Closed** 2020-09-23 16:44 UTC
