### ISSUE TITLE
Spaces in string removed

### ISSUE THREAD

**Issue by ThomasVandezande** [dfinke/ImportExcel#184] opened 2017-05-04 15:38 UTC
first of all,  i love the functions provided here.
But , when exporting a productnumber to an excel sheet the spaces in my string are removed when exporting to Excel.
In Posh my datatype is string and displayed as following:
![image](https://cloud.githubusercontent.com/assets/28398383/25711572/904618bc-30ef-11e7-9b4d-f2ad786671e3.png)

When Exporting to CSV i get the following result:
![image](https://cloud.githubusercontent.com/assets/28398383/25711613/a7d2e5e6-30ef-11e7-9ce6-4bb715f7c069.png)

When Exporting to Excel I get the following values:
![image](https://cloud.githubusercontent.com/assets/28398383/25711725/eb471ed2-30ef-11e7-9330-d9618b2160eb.png)

Snippet of code used to perform my exports:
 `$result |  Select * -ExcludeProperty RowError, RowState, HasErrors, Table, ItemArray | Export-Excel $filename -autosize -autofilter -Numberformat '#'`
`#For testing`
`$result |  Select * -ExcludeProperty RowError, RowState, HasErrors, Table, ItemArray | Export-Csv C:\Temp\test.csv`

Looks to me that somewhere in de 'export-excel' process the spaces in my numbers are removed. But they should be treated as strings rather than numbers.

**Comment by dfinke** [comment] 2017-05-04 17:26
Hmmm. I can't reproduce that.

![image](https://cloud.githubusercontent.com/assets/67258/25716478/28dd8c40-30cd-11e7-8138-676066f221bb.png)

**Comment by ThomasVandezande** [comment] 2017-05-05 07:31
[test.txt](https://github.com/dfinke/ImportExcel/files/978329/test.txt)

Hi,
thanks for getting to me so quickly.
in attachment you'll find an CSV export (renamed to .txt for allowing upload here).

When i use the following code , this still produces my issue:
`$resultset = Import-Csv c:\temp\test.csv -Delimiter ','`
`$resultset | Export-Excel -now`

![image](https://cloud.githubusercontent.com/assets/28398383/25736985/8f96f8a6-3175-11e7-9586-c0c494a37beb.png)

I was also thinking it might have something to do with the 'locale settings'? Could you provide me yours so I can run some tests on that as well?

**Comment by dfinke** [comment] 2017-05-05 19:19
Hmm, that worked for me.

What version of importexcel do you have?
```powershell
get-module -list importexcel
```

Also you don't need the `-Delimiter ','` on the `Import-Csv`, that's the default

**Comment by ThomasVandezande** [comment] 2017-05-10 09:41
@dfinke  , sorry for the late reply. The version is installed is 2.4.0.

![image](https://cloud.githubusercontent.com/assets/28398383/25892735/a096687c-3575-11e7-9a72-9a0e1aea7d8b.png)

**Comment by DarkLite1** [comment] 2017-08-21 15:26
This has been implemented with the `-NoNumberConversion` parameter in `Export-Excel` recently. The following should solve your problem:

```
$resultset = Import-Csv c:\temp\test.csv 
$resultset | Export-Excel -Now -NoNumberConversion ItemNr
```

@dfinke I think this can be closed as solved.

**Closed** 2017-08-22 10:57 UTC
Labels: Investigate
