### ISSUE TITLE
Import-Excel accepts the PipelineVariable param, but the variable stays empty.

### ISSUE THREAD

**Issue by lucdekens** [dfinke/ImportExcel#718] opened 2019-11-08 13:48 UTC
Looks like this PipelineVariable on the Import-Excel cmdlet might not be working as expected.
The variable seems to stay empty.

Tested this on 6.5.2
![2019-11-08_14-32-23](https://user-images.githubusercontent.com/7760649/68481081-8d47bd80-0236-11ea-81ac-6f84504159b5.jpg)

Boe Prox did a post on how to implement the PipelineVariable parameter.
See https://mcpmag.com/articles/2016/12/15/pipelinevariable-common-parameter.aspx

**Comment by ili101** [comment] 2019-11-15 14:59
I see that someone opened an issue on it 17 days ago https://github.com/PowerShell/PowerShell/issues/10932
Basically if you want -PipelineVariable to work you can't use Begin, Process, End as it will work only on the first thing in the pipeline.
👍 on https://github.com/PowerShell/PowerShell/issues/10932 and maybe they will tell us if it's a bug or intended behavior.

**Comment by lucdekens** [comment] 2019-11-15 16:05
I'm not too sure if this is applicable in this case.
The sample I used above is not using an advanced function, nor any Begin/Process/End blocks.

**Comment by ili101** [comment] 2019-11-15 16:22
Import-Excel itself is an advanced function with Begin/Process/End.
For this to work (if not fixed in newer version of PowerShell at some point) we need to rewrite Import-Excel without Begin/Process/End

**Comment by ili101** [comment] 2019-11-15 16:49
Actually as the only Pipeline parameter is -Path I just removed the Begin/Process/End and looks like it works without any side effects that I can see, try loading this https://gist.github.com/ili101/a8d7b3bfedad159cfc6f667d88b6395c Import-Excel and try your command again, it should work.

**Comment by lucdekens** [comment] 2019-11-15 19:01
Confirmed, that does the trick

**Comment by dfinke** [comment] 2019-11-15 19:03
Thanks @ili101 do the unit tests work with that change? Can you add some to handle this scenario and do a PR?

**Closed** 2020-05-02 14:28 UTC
Labels: Investigate
